### ISSUE TITLE
bug report: root.GeneratedTypes undefined

### ISSUE THREAD

**Issue by shoot16625** [NagayamaRyoga/goalint#1]
Thank you for providing such a great tool !!

Due to recent goa changes, Latest goa v3 doesn't have `GeneratedTypes` in RootExpr. ([Ref](https://github.com/goadesign/goa/commit/4d06dd659a3572a3be44d365fc0fbdef05fb899f#diff-08226492e68a4e417237dc59a6aff3736b537e4550148e5e262f45951110a5bfL30))
So fail to exec run command like this.

```
go run github.com/NagayamaRyoga/goalint/cmd/goalint github.com/xxxx/goa/design
# github.com/NagayamaRyoga/goalint/pkg/common/walk
../../../../go/pkg/mod/github.com/!nagayama!ryoga/goalint@v0.0.0-20240316122113-c5eb82733c09/pkg/common/walk/walk.go:53:12: root.GeneratedTypes undefined (type *expr.RootExpr has no field or method GeneratedTypes)
../../../../go/pkg/mod/github.com/!nagayama!ryoga/goalint@v0.0.0-20240316122113-c5eb82733c09/pkg/common/walk/walk.go:54:30: root.GeneratedTypes undefined (type *expr.RootExpr has no field or method GeneratedTypes)
cmd.Run() failed: exec.Command("/opt/homebrew/bin/go build -o ./goalint1931821103/a.out ./goalint1931821103/main.go").Run() failed: exit status 1
exit status 255
```

I'd be happy if you could just check it out !!

**Comment by NagayamaRyoga** [comment]
Thank you for your report. Please check #2 to see if it has been fixed.

**Comment by shoot16625** [comment]
Thank you for your quick fix. It's now working properly!
